@HotelListing.API_HostAddress = https://localhost:7227

GET {{HotelListing.API_HostAddress}}/api/countries


### Working

GET {{HotelListing.API_HostAddress}}/api/countries/{{id}}

### Working

POST {{HotelListing.API_HostAddress}}/api/countries
Content-Type: application/json

{
  "Name": "Turkey",
  "ShortName": "TR"
}

### Working

DELETE {{HotelListing.API_HostAddress}}/api/countries/{{id}}

### Working

PUT {{HotelListing.API_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "id": 4,
  "name": "United States of America",
  "shortName": "USA"
}

### Working




GET {{HotelListing.API_HostAddress}}/api/hotels

### Working

GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

### Working

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name" : "Grand USA Hotel",
  "Address" : "Washington DC",
  "Rate" : 4.5,
  "CountryId" : 4
}

### Working

DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

### Working

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id" : 1,
  "Name" : "Grand USA 2 Hotel",
  "Address" : "New York",
  "Rate" : 4,
  "CountryId" : 4
}

### Working


